PACKAGE_NAME="hid_t2magicmouse"
PACKAGE_VERSION="0.1"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="hid_t2magicmouse"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
