Syntax 4

Define.SpeakerChannels 2
Define.SpeakerChannel0 0
Define.SpeakerChannel1 1
Define.SpeakerChannelPos0 FL
Define.SpeakerChannelPos1 FR

SectionUseCase."HiFi" {
	File "/AppleT2/HiFi.conf"
	Comment "Apple T2 Audio"
}
