Syntax 4

Define.SpeakerChannels 6
Define.SpeakerChannel0 0
Define.SpeakerChannel1 1
Define.SpeakerChannel2 2
Define.SpeakerChannel3 3
Define.SpeakerChannel4 4
Define.SpeakerChannel5 5
Define.SpeakerChannelPos0 FL
Define.SpeakerChannelPos1 SL
Define.SpeakerChannelPos2 RL
Define.SpeakerChannelPos3 FR
Define.SpeakerChannelPos4 SR
Define.SpeakerChannelPos5 RR

SectionUseCase."HiFi" {
	File "/AppleT2/HiFi.conf"
	Comment "Apple T2 Audio"
}
