#!/bin/bash
if [ "$1" = remove ]; then
    if ! bash /usr/libexec/t2-dsp/package-actions removed; then
        echo '[t2-dsp] error: cleanup helper failed' >&2
        echo 'cleanup helper failed' >> /var/log/t2-dsp-install.log || echo '[t2-dsp] error: cannot save report' >&2
    fi
fi
#DEBHELPER#
exit 0
