PACKAGE_NAME="t2smc"
PACKAGE_VERSION="0.1"

MAKE[0]="make KERNEL_SRC=/lib/modules/${kernelver}/build KERNEL_RELEASE=${kernelver}"

BUILT_MODULE_NAME[0]="t2smc"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
