PACKAGE_NAME="brcmfmac_kait2en"
PACKAGE_VERSION="7.1.6_kait2en2"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="brcmfmac"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
