#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Seed/check the source-to-package transition in disposable containers only."""
import argparse
from pathlib import Path
import shutil

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("action", choices=["seed", "installed", "removed"])
parser.add_argument("source", type=Path)
args = parser.parse_args()
if not Path("/run/.containerenv").exists() and not Path("/.dockerenv").exists():
    raise SystemExit("Refusing to seed package fixtures outside a container")

old_unit = Path("/etc/systemd/system/t2-services-suspend.service")
old_helper = Path("/usr/local/libexec/t2-services/t2-ncm-sleep")
old_profile = Path("/etc/NetworkManager/system-connections/old-kait2en.nmconnection")
old_dsp = Path("/usr/share/kait2en/audio-dsp")
old_conf = Path("/etc/wireplumber/wireplumber.conf.d/51-kait2en-t2-dsp.conf")
uuid = "7de922f7-0659-4f15-8c82-36c45450b78c"

if args.action == "seed":
    shared = args.source / "t2-services/shared/integration"
    for path in (old_unit, old_helper, old_profile, old_conf):
        path.parent.mkdir(parents=True, exist_ok=True)
    old_unit.write_text((shared / "systemd/t2-services-suspend.service").read_text().replace("@LIBEXECDIR@", "/usr/local/libexec"))
    enabled = old_unit.parent / "sleep.target.wants/t2-services-suspend.service"
    enabled.parent.mkdir(parents=True, exist_ok=True)
    enabled.symlink_to(old_unit)
    shutil.copyfile(shared / "libexec/t2-ncm-sleep", old_helper)
    old_profile.write_text((shared / "NetworkManager/t2-ncm.nmconnection").read_text().replace("6ab6bd67-a58f-47a6-a7c5-b03c2de64f2b", uuid))
    old_profile.chmod(0o600)
    shutil.copytree(args.source / "dsp/profiles", old_dsp)
    old_conf.write_text("# Generated by scripts/fedora/install-dsp.sh for MacBookPro15,1\n")
elif args.action == "installed":
    for path in (old_unit, old_helper, old_profile, old_conf, old_dsp):
        assert not path.exists(), f"Legacy path still present: {path}"
    assert uuid in Path("/etc/NetworkManager/system-connections/t2-ncm.nmconnection").read_text()
    assert Path("/etc/systemd/system/sleep.target.wants/t2-services-suspend.service").resolve().is_file()
    for component in ("t2-services-common", "t2-dsp"):
        assert Path(f"/var/lib/kait2en/ownership/{component}.json").is_file()
        assert any(Path(f"/var/lib/kait2en/migration/{component}").iterdir())
else:
    for component in ("t2-services-common", "t2-dsp"):
        assert not Path(f"/var/lib/kait2en/ownership/{component}.json").exists()
        assert not Path(f"/var/lib/kait2en/migration/{component}").exists()
    for path in (old_unit, old_helper, old_profile, old_conf, old_dsp):
        assert not path.exists()
print(f"PASS: source/package fixture {args.action}")
