Include.pcm_split.File "/common/pcm/split.conf"

Macro.playback.SplitPCM {
	Name "apple_t2_speakers"
	Direction Playback
	Format S24_LE
	Channels "${var:SpeakerChannels}"
	HWChannels "${var:SpeakerChannels}"
	HWChannelPos0 "${var:SpeakerChannelPos0}"
	HWChannelPos1 "${var:SpeakerChannelPos1}"
	HWChannelPos2 "${var:-SpeakerChannelPos2}"
	HWChannelPos3 "${var:-SpeakerChannelPos3}"
	HWChannelPos4 "${var:-SpeakerChannelPos4}"
	HWChannelPos5 "${var:-SpeakerChannelPos5}"
}

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Internal Speakers"

	Value {
		PlaybackPriority 100
	}
	Macro.pcm_split.SplitPCMDevice {
		Name "apple_t2_speakers"
		Direction Playback
		Device 0
		Channels "${var:SpeakerChannels}"
		HWChannels "${var:SpeakerChannels}"
		Channel0 "${var:SpeakerChannel0}"
		Channel1 "${var:SpeakerChannel1}"
		Channel2 "${var:-SpeakerChannel2}"
		Channel3 "${var:-SpeakerChannel3}"
		Channel4 "${var:-SpeakerChannel4}"
		Channel5 "${var:-SpeakerChannel5}"
		ChannelPos0 "${var:SpeakerChannelPos0}"
		ChannelPos1 "${var:SpeakerChannelPos1}"
		ChannelPos2 "${var:-SpeakerChannelPos2}"
		ChannelPos3 "${var:-SpeakerChannelPos3}"
		ChannelPos4 "${var:-SpeakerChannelPos4}"
		ChannelPos5 "${var:-SpeakerChannelPos5}"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	ConflictingDevice [
		"Headset"
	]

	Value {
		CapturePriority 300
		CaptureChannels 3
		CaptureRate 48000
		CapturePCM "hw:${CardId},1"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	ConflictingDevice [
		"Speaker"
	]

	Value {
		PlaybackPriority 300
		PlaybackChannels 2
		PlaybackPCM "hw:${CardId},2"
		JackControl "Codec Output Jack"
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	ConflictingDevice [
		"Mic"
	]

	Value {
		CapturePriority 200
		CaptureChannels 1
		CapturePCM "hw:${CardId},3"
		JackControl "Codec Output Jack"
	}
}
