#!/bin/sh
if [ -d /run/systemd/system ]; then
    if ! systemctl daemon-reload; then
        echo '[t2-services] error: systemd reload after removal failed' >&2
        echo 't2-journal: systemd reload after removal failed' >> /var/log/t2-services-install.log || echo '[t2-services] error: cannot save report' >&2
    fi
fi
#DEBHELPER#
exit 0
