# KaiT2en DSP scheduling default.
# Administrators may override this fragment in /etc/pipewire/pipewire.conf.d/.
context.properties = {
    default.clock.quantum = 1024
    default.clock.min-quantum = 1024
}
