Syntax 4

Define.SpeakerChannels 4
Define.SpeakerChannel0 0
Define.SpeakerChannel1 1
Define.SpeakerChannel2 2
Define.SpeakerChannel3 3
Define.SpeakerChannelPos0 FL
Define.SpeakerChannelPos1 FR
Define.SpeakerChannelPos2 RL
Define.SpeakerChannelPos3 RR

SectionUseCase."HiFi" {
	File "/AppleT2/HiFi.conf"
	Comment "Apple T2 Audio"
}
